language: node_js
node_js:
- '8'
services:
- mongodb
addons:
  sonarcloud:
    organization: moser-ss-github
    token:
      secure: RqgCfv3viZRz5n5Doqcc1Q9/LtQIeZah4hfFkMbwaxcSlzdZm7ZNMOGCUrqS2/URbdS/E3ydp+69uKxg4CdwyBxEBN97uhrS5qGqzge21yLR/hsb36bi4LaL7qUoJ7tb1ayt7Mx2CjBkxtAfwwh5aFaW0tY+dsngSkgvKZiqYxKmagpjHsjKGKsOTC4kfV33sjAO+6Y/xYXP5PiARVmMIxQljFtk69Bo9+2JGVGOqLJp3CXoZ3JPbfEaRUEiq09OlC28UtICwWqIZdnmGFsxOa6LvHmpphZ/UIxcXIkk/NgdzzAR4t1+58EkKrcGWWSllyeq3xtvHXOO94RYdc8DiUqq5jZnE30BaK4qS58xHFwVKtvs3t7CBs+2QF01HeF4Yhi1UjhN4LeKm4I8xUvYNjnREhx5iFS7RhnfG8Cw9PdT+z2eTkMOibrZCOnuoF9F9SjYEiA2+zdU2zaTZ1weAu8CxxjZTWDpH8dakJT5aHQwQD0XHD64qPAckvsysxQ5YKaoFvqcYRqGB+1gF3KhIfpXhKhaLn7B5q6FCa2SdHZ1ve/SPIgDtEjAvPd/V9ENJB3j5b3tM9iKKExm0XQA+6f9vmzey15k7A657kLfqgRgv0Z3LseLRxZYO0ohd8dKGurqo/u6pEGcBY7lIHBQNsUn10N8bty+FIylYhRIcvo=
script:
- npm run test-coverage
- sonar-scanner
branches:
  only:
  - master
deploy:
  provider: heroku
  api_key:
    secure: A0SbfgYRivo+t3hocQI3cA7woY+mcfENj2h2yw7J3PcaBnEIJ8vnmk+SDRPLo7N0ICnJrN7v8rdDGjCG5ReQOkBKYEsvnKUML9iC0ceFAdRTJuck5MZfFt78uwXPp6Cc8X/qSAmGRirzRqOrX0SITXOKD6T+cKtemNv7pJjvVXTOVt6d1XysMykZkhkYAxtHDER37ZcUxQb4c/XmmyncQiGHXdkpi916Q3Pzoj2/Z7hAWeEbeMEPGe6J5M7LQjxn/dfhnoYwoG/BwBNLRTHCTb4RFDW0PYWrLRhVtYHwsd74/Sb1lUSKc/3XymUBjU0lP1Zx0SzBsBfhHG1WScVLyfyO57a+eQKM893a6iscaJ19Qy2RUE16VdKB+1FA+WGZKUk2b/sXiybN76AWxr6fts50N27zs7SoJg1yrmQb/8AZKCh9aLgtxKlaFunnZHqXir9YuDOmOi3cTifFShkDAleAMNMjkICwPrGiIa0cFUz8V/f2p2hr3kbDIVi4ljj6XBP/XQmhH9LwbYjm6CnIYCdompHkAvN3AH/O81ncWyvK0Rb3aHr6zTZRKtVClMMOpI3fDyiQn+2OyBKksJmg93NtHUlWmLd7jC2C96R7KZIqh2P7Awi01VajJQcy0FWXNGDu0uHiMH0mzomfQ4yRS1awmpgkPdO/9P8m+0KWEpA=
  app: tranquil-ridge-45172
  on:
    repo: Moser-ss/node-course-todo-api
