language: node_js
node_js:
- '8'
services:
- mongodb
addons:
  sonarcloud:
    organization: moser-ss-github
    token:
      secure: RqgCfv3viZRz5n5Doqcc1Q9/LtQIeZah4hfFkMbwaxcSlzdZm7ZNMOGCUrqS2/URbdS/E3ydp+69uKxg4CdwyBxEBN97uhrS5qGqzge21yLR/hsb36bi4LaL7qUoJ7tb1ayt7Mx2CjBkxtAfwwh5aFaW0tY+dsngSkgvKZiqYxKmagpjHsjKGKsOTC4kfV33sjAO+6Y/xYXP5PiARVmMIxQljFtk69Bo9+2JGVGOqLJp3CXoZ3JPbfEaRUEiq09OlC28UtICwWqIZdnmGFsxOa6LvHmpphZ/UIxcXIkk/NgdzzAR4t1+58EkKrcGWWSllyeq3xtvHXOO94RYdc8DiUqq5jZnE30BaK4qS58xHFwVKtvs3t7CBs+2QF01HeF4Yhi1UjhN4LeKm4I8xUvYNjnREhx5iFS7RhnfG8Cw9PdT+z2eTkMOibrZCOnuoF9F9SjYEiA2+zdU2zaTZ1weAu8CxxjZTWDpH8dakJT5aHQwQD0XHD64qPAckvsysxQ5YKaoFvqcYRqGB+1gF3KhIfpXhKhaLn7B5q6FCa2SdHZ1ve/SPIgDtEjAvPd/V9ENJB3j5b3tM9iKKExm0XQA+6f9vmzey15k7A657kLfqgRgv0Z3LseLRxZYO0ohd8dKGurqo/u6pEGcBY7lIHBQNsUn10N8bty+FIylYhRIcvo=
script:
- npm run test-coverage
- sonar-scanner
deploy:
  provider: heroku
  api_key:
    secure: HeaihBbqA+84nD5DEIl8/aOC+6aJ0Ts+6J7749P1D1Tk6RbfBoO9Awx7GukOcvWnBk95S+J0Ksa+VNwjT9WU1dQmVzq71FAR9Y0cVyBWsXqbrUKGEUqKWkNJt0v6vne2alRjcRFnm/qxfGeBNaA10HEaK4UPuz/3Euzmo+DwYUm2cI9awXNOXnj6Zso30zUVzNuz1QUvmsZM1Hnk/VnvQkbJfo1fvAUa7mAbqfvYfYrxCTo40sr/9Hegd8xTQXwJN96VfLq/kl7DQMfSRqt21QYm1qAhMpCdN5LyA+iCTRwc2rZqdaZI8uNHnXE9RqT+bPaNeTFqHtE0/6eDZeJ84f3C7oD/Bynf+7DFXSdRvviH1KoBxXEJhXfjhSQS1t6wKEzvJfJrdkJcb9/9bEXp+pw9xOjPy0qhxB/iFwwNn+Ai7iOQJ/2yAdjjabY+/2hDz09QUsgeJdg1qAUan3HQFGw91ilTJeDxrzzP8Z2BmdxZ4YrZuXfSQNoZXzTSp59DSqoc4Tu0nOY7HzZ91/EwYnedpyWWUsIEZAzfMLrxewNJ9/ipPtOhvoxqCZ7gzDUmAuxug93K+O33m9MCt2XuQeOlHHcqJcm4TCExV+R6Czm5uN4vffC+WtJ6ElEn9My87zfTCoA0eFGP+RV1TiVaF9Rr5y1gTkZjRXCsa5Ts94g=
  app: moser-ss-todo-api
