name: Auto merge

on:
  push:
    branches-ignore:
      - master
      
  status:
jobs:
  auto-merge:
    name: Auto merge
    runs-on: ubuntu-latest
    steps:
      - name: Snyk auto merge
        uses: ridedott/merge-me-action@master
        with:
          GITHUB_LOGIN: snyk-bot
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
