name: Auto merge

on:
  check_suite:
    types:
      - completed
jobs:
  auto-merge:
    name: Auto merge
    runs-on: ubuntu-latest
    steps:
      - name: Snyk auto merge
        uses: ridedott/merge-me-action@master
        with:
          GITHUB_LOGIN: snyk-bot
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
